server:
  port: 8080

spring:
  application:
    name: PAY
  profiles:
    active: druid
  redis:
    port:
    password:
    host:
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: moonlit.chill.pay.**.vo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
